$msoLanguageIDDutch = 1043 # Word variabele
$msoLanguageIDEnglishUS = 1033 # Word variabele
$wdAdjustNone = 0 # Word variabele
$wdAutoFitFixed = 0 # Word variabele
$wdAlignParagraphCenter = 1 # Word variabele
$wdBorderLeft = -2 # Word variabele
$wdBorderRight = -4 # Word variabele
$wdBorderTop = -1 # Word variabele
$wdBorderBottom = -3 # Word variabele
$wdBorderHorizontal = -5 # Word variabele
$wdBorderVertical = -6 # Word variabele
$wdBorderDiagonalDown = -7 # Word variabele
$wdBorderDiagonalUp = -8 # Word variabele
$wdBulletGallery = 1 # Word variabele
$wdCell = 12 # Word variabele
$wdCharacter = 1 # Word variabele
$wdColumn = 9 # Word variabele
$wdExtend = 1 # Word variabele
$wdFieldEmpty = -1 # Word variabele
$wdFormatXMLDocument = 12 # Word variabele
$wdGoToBookmark = -1 # Word variabele
$wdLine=5 # Word variabele
$wdLineStyleNone = 0 # Word variabele
$wdNumberParagraph = 1 # Word variabele
$wdPageBreak = 7 # Word variabele
$wdRow = 10 # Word variabele
$wdStory = 6 # Word variabele
$wdTable = 15 # Word variabele
$wdToggle=9999998  # Word variabele
$wdUnderlineNone =0 # Word variabele
$wdUnderlineSingle =1 # Word variabele
$Wdword = 2 # Word variabele
$wdWord9TableBehavior = 1 # Word variabele
$wdPropertyTitle = 1    # Word variabele
$wdSeekMainDocument = 0 # Word variabele
$wdSeekCurrentPageHeader = 9 # Word variabele
$wdSeekCurrentPageFooter = 10 # Word variabele
$Quote = [Char]34 #Variabele om een Quote weer te geven
$Tab = [Char]9 #Variabele om een tab weer te geven